### ISSUE TITLE
Build instructions ?

### ISSUE THREAD

**Issue by purpl3F0x** [Inrixia/TidalTags#3]
Hello, can you provide some build instructions ? I want to make some visual changes to match the tidal UI, but don't have much experience with nodejs

**Comment by purpl3F0x** [comment]
Nevermind it needed a clean build for the first time. 
I was doind build:chrome directly

**Comment by Inrixia** [comment]
If you are making changes please lemme know how they look. I'm currently working on implementing this on the desktop app (https://github.com/Inrixia/neptune-plugins) and am thinking about deprecating the web version.

**Comment by purpl3F0x** [comment]
![image](https://github.com/Inrixia/TidalTags/assets/16735391/8d7d44b9-2fa5-456c-b4b7-790772c4ce7c)
![image](https://github.com/Inrixia/TidalTags/assets/16735391/1ba052e7-c17c-431a-9c07-dc722ee0faa7)
I also replaced the Atmos text with ◗, but i can't get it to show at any album

Btw, probably it should only show HighRes and not MQA, in the second case.
